var hierarchy =
[
    [ "Application", null, [
      [ "Game::App", "class_game_1_1_app.html", null ],
      [ "Game::App", "class_game_1_1_app.html", null ],
      [ "Game::App", "class_game_1_1_app.html", null ]
    ] ],
    [ "ApplicationSettingsBase", null, [
      [ "Game::Properties::Settings", "class_game_1_1_properties_1_1_settings.html", null ]
    ] ],
    [ "Game.Scripts.HighscoreData.Data", "class_game_1_1_scripts_1_1_highscore_data_1_1_data.html", null ],
    [ "Game.Scripts.Player.Data", "class_game_1_1_scripts_1_1_player_1_1_data.html", null ],
    [ "Game.Scripts.Session.Data", "class_game_1_1_scripts_1_1_session_1_1_data.html", null ],
    [ "IComponentConnector", null, [
      [ "Game::Controls::Board", "class_game_1_1_controls_1_1_board.html", null ],
      [ "Game::Controls::Board", "class_game_1_1_controls_1_1_board.html", null ],
      [ "Game::Controls::Card", "class_game_1_1_controls_1_1_card.html", null ],
      [ "Game::Controls::Card", "class_game_1_1_controls_1_1_card.html", null ],
      [ "Game::Controls::CardSelect", "class_game_1_1_controls_1_1_card_select.html", null ],
      [ "Game::Controls::CardSelect", "class_game_1_1_controls_1_1_card_select.html", null ],
      [ "Game::Controls::CustomTextbox", "class_game_1_1_controls_1_1_custom_textbox.html", null ],
      [ "Game::Controls::CustomTextbox", "class_game_1_1_controls_1_1_custom_textbox.html", null ],
      [ "Game::Controls::HighscoreContainer", "class_game_1_1_controls_1_1_highscore_container.html", null ],
      [ "Game::Controls::HighscoreContainer", "class_game_1_1_controls_1_1_highscore_container.html", null ],
      [ "Game::Controls::ImageButton", "class_game_1_1_controls_1_1_image_button.html", null ],
      [ "Game::Controls::ImageButton", "class_game_1_1_controls_1_1_image_button.html", null ],
      [ "Game::Controls::Modal", "class_game_1_1_controls_1_1_modal.html", null ],
      [ "Game::Controls::Modal", "class_game_1_1_controls_1_1_modal.html", null ],
      [ "Game::Controls::ModalContent::ModalContentEndResult", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_end_result.html", null ],
      [ "Game::Controls::ModalContent::ModalContentEndResult", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_end_result.html", null ],
      [ "Game::Controls::ModalContent::ModalContentPause", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_pause.html", null ],
      [ "Game::Controls::ModalContent::ModalContentPause", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_pause.html", null ],
      [ "Game::Controls::ModalPause", "class_game_1_1_controls_1_1_modal_pause.html", null ],
      [ "Game::Controls::ModelPause", "class_game_1_1_controls_1_1_model_pause.html", null ],
      [ "Game::Controls::PlayerView", "class_game_1_1_controls_1_1_player_view.html", null ],
      [ "Game::Controls::PlayerView", "class_game_1_1_controls_1_1_player_view.html", null ],
      [ "Game::MainWindow", "class_game_1_1_main_window.html", null ],
      [ "Game::MainWindow", "class_game_1_1_main_window.html", null ],
      [ "Game::Pages::PageGame", "class_game_1_1_pages_1_1_page_game.html", null ],
      [ "Game::Pages::PageGame", "class_game_1_1_pages_1_1_page_game.html", null ],
      [ "Game::Pages::PageHighscores", "class_game_1_1_pages_1_1_page_highscores.html", null ],
      [ "Game::Pages::PageHighscores", "class_game_1_1_pages_1_1_page_highscores.html", null ],
      [ "Game::Pages::PageMenu", "class_game_1_1_pages_1_1_page_menu.html", null ],
      [ "Game::Pages::PageMenu", "class_game_1_1_pages_1_1_page_menu.html", null ],
      [ "Game::Pages::PageSettings", "class_game_1_1_pages_1_1_page_settings.html", null ],
      [ "Game::Pages::PageSettings", "class_game_1_1_pages_1_1_page_settings.html", null ]
    ] ],
    [ "Game.Scripts.ImageDefinition", "class_game_1_1_scripts_1_1_image_definition.html", null ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace::GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace::GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "NavigationWindow", null, [
      [ "Game::MainWindow", "class_game_1_1_main_window.html", null ],
      [ "Game::MainWindow", "class_game_1_1_main_window.html", null ],
      [ "Game::MainWindow", "class_game_1_1_main_window.html", null ]
    ] ],
    [ "Page", null, [
      [ "Game::Pages::PageGame", "class_game_1_1_pages_1_1_page_game.html", null ],
      [ "Game::Pages::PageGame", "class_game_1_1_pages_1_1_page_game.html", null ],
      [ "Game::Pages::PageHighscores", "class_game_1_1_pages_1_1_page_highscores.html", null ],
      [ "Game::Pages::PageHighscores", "class_game_1_1_pages_1_1_page_highscores.html", null ],
      [ "Game::Pages::PageMenu", "class_game_1_1_pages_1_1_page_menu.html", null ],
      [ "Game::Pages::PageMenu", "class_game_1_1_pages_1_1_page_menu.html", null ],
      [ "Game::Pages::PageSettings", "class_game_1_1_pages_1_1_page_settings.html", null ],
      [ "Game::Pages::PageSettings", "class_game_1_1_pages_1_1_page_settings.html", null ]
    ] ],
    [ "Page", null, [
      [ "Game::Pages::PageGame", "class_game_1_1_pages_1_1_page_game.html", null ],
      [ "Game::Pages::PageHighscores", "class_game_1_1_pages_1_1_page_highscores.html", null ],
      [ "Game::Pages::PageMenu", "class_game_1_1_pages_1_1_page_menu.html", null ],
      [ "Game::Pages::PageSettings", "class_game_1_1_pages_1_1_page_settings.html", null ]
    ] ],
    [ "Game.Scripts.Player", "class_game_1_1_scripts_1_1_player.html", null ],
    [ "Game::Properties::Resources", "class_game_1_1_properties_1_1_resources.html", null ],
    [ "Game.Scripts.Session", "class_game_1_1_scripts_1_1_session.html", null ],
    [ "Game.Scripts.SessionData", "class_game_1_1_scripts_1_1_session_data.html", null ],
    [ "UserControl", null, [
      [ "Game::Controls::Board", "class_game_1_1_controls_1_1_board.html", null ],
      [ "Game::Controls::Board", "class_game_1_1_controls_1_1_board.html", null ],
      [ "Game::Controls::Board", "class_game_1_1_controls_1_1_board.html", null ],
      [ "Game::Controls::Card", "class_game_1_1_controls_1_1_card.html", null ],
      [ "Game::Controls::Card", "class_game_1_1_controls_1_1_card.html", null ],
      [ "Game::Controls::Card", "class_game_1_1_controls_1_1_card.html", null ],
      [ "Game::Controls::CardSelect", "class_game_1_1_controls_1_1_card_select.html", null ],
      [ "Game::Controls::CardSelect", "class_game_1_1_controls_1_1_card_select.html", null ],
      [ "Game::Controls::CardSelect", "class_game_1_1_controls_1_1_card_select.html", null ],
      [ "Game::Controls::CustomTextbox", "class_game_1_1_controls_1_1_custom_textbox.html", null ],
      [ "Game::Controls::CustomTextbox", "class_game_1_1_controls_1_1_custom_textbox.html", null ],
      [ "Game::Controls::CustomTextbox", "class_game_1_1_controls_1_1_custom_textbox.html", null ],
      [ "Game::Controls::HighscoreContainer", "class_game_1_1_controls_1_1_highscore_container.html", null ],
      [ "Game::Controls::HighscoreContainer", "class_game_1_1_controls_1_1_highscore_container.html", null ],
      [ "Game::Controls::HighscoreContainer", "class_game_1_1_controls_1_1_highscore_container.html", null ],
      [ "Game::Controls::ImageButton", "class_game_1_1_controls_1_1_image_button.html", null ],
      [ "Game::Controls::ImageButton", "class_game_1_1_controls_1_1_image_button.html", null ],
      [ "Game::Controls::ImageButton", "class_game_1_1_controls_1_1_image_button.html", null ],
      [ "Game::Controls::Modal", "class_game_1_1_controls_1_1_modal.html", null ],
      [ "Game::Controls::Modal", "class_game_1_1_controls_1_1_modal.html", null ],
      [ "Game::Controls::Modal", "class_game_1_1_controls_1_1_modal.html", null ],
      [ "Game::Controls::ModalContent::ModalContentEndResult", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_end_result.html", null ],
      [ "Game::Controls::ModalContent::ModalContentEndResult", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_end_result.html", null ],
      [ "Game::Controls::ModalContent::ModalContentEndResult", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_end_result.html", null ],
      [ "Game::Controls::ModalContent::ModalContentPause", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_pause.html", null ],
      [ "Game::Controls::ModalContent::ModalContentPause", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_pause.html", null ],
      [ "Game::Controls::ModalContent::ModalContentPause", "class_game_1_1_controls_1_1_modal_content_1_1_modal_content_pause.html", null ],
      [ "Game::Controls::ModalPause", "class_game_1_1_controls_1_1_modal_pause.html", null ],
      [ "Game::Controls::ModelPause", "class_game_1_1_controls_1_1_model_pause.html", null ],
      [ "Game::Controls::PlayerView", "class_game_1_1_controls_1_1_player_view.html", null ],
      [ "Game::Controls::PlayerView", "class_game_1_1_controls_1_1_player_view.html", null ],
      [ "Game::Controls::PlayerView", "class_game_1_1_controls_1_1_player_view.html", null ]
    ] ]
];